"""Project adoption: overlaying the docs-first workflow onto existing projects."""

from __future__ import annotations

import os
import shutil
from pathlib import Path

import tomlkit

from prothon.adoption_templates import (
    _AGENTS_CONTENT,
    _DESIGN_SCAFFOLD,
    _GITLAB_VERSION_BUMP,
    _PATTERNS_SCAFFOLD,
    _REFERENCES_MODULES_HEADER,
    _SPEC_SCAFFOLD,
    _VERSION_BUMP_WORKFLOW,
    _VERSION_TAG_WORKFLOW,
)
from prothon.ast_miner import ASTPatternMiner
from prothon.exceptions import GitError, ProjectAlreadyInitError, ProthonError
from prothon.git import run_git
from prothon.scaffold import get_template_dir


def _run_copier_init(dest: Path, data: dict[str, str]) -> None:
    """Run Copier for project adoption (no git init, no commits).

    Args:
        dest: Destination directory for the generated files.
        data: Pre-filled answers dict from _collect_project_details().
    """
    from copier import run_copy

    run_copy(
        str(get_template_dir()),
        str(dest),
        data=data,
        defaults=True,
        unsafe=True,
        skip_tasks=True,
        skip_if_exists=["**"],
        exclude=["docs/*", "AGENTS.md*"],
        vcs_ref="HEAD",
    )


def init_existing(
    cwd: Path | None = None, data: dict[str, str] | None = None
) -> list[Path]:
    """Overlay the docs-first workflow onto an existing project.

    When pyproject.toml is absent (Path A), uses provided project details
    to scaffold the Python project structure via Copier before applying
    the common overlay. Files generated by Copier are not included in the
    returned list.

    When pyproject.toml is present (Path B), Copier is skipped and only
    the common overlay files are created.

    Args:
        cwd: Directory to adopt. Defaults to the current working directory.
        data: Optional project details (required if pyproject.toml is missing).

    Returns:
        List of created documentation and workflow files.

    Raises:
        ProjectAlreadyInitError: If docs/SPEC.md already exists.
        GitError: If the target directory is not a git repository.
        ProthonError: If adoption details are missing for Path A.
    """
    root = cwd or Path.cwd()

    # Verify git repository
    try:
        run_git("rev-parse", "--is-inside-work-tree", cwd=root)
    except GitError:
        msg = "not a git repository"
        raise GitError(msg)

    spec_path = root / "docs" / "SPEC.md"
    if spec_path.exists():
        msg = "docs/SPEC.md already exists"
        raise ProjectAlreadyInitError(msg)

    pyproject_path = root / "pyproject.toml"
    if not pyproject_path.exists():
        if not data:
            msg = "project details required for adoption (no pyproject.toml found)"
            raise ProthonError(msg)
        # Path A: Scaffold structure via Copier first
        _run_copier_init(root, data)

    # Path A & B: Common workflow overlay
    created = []

    # 1. Create core documents (SPEC, DESIGN, PATTERNS)
    created.extend(_create_docs(root))

    # 2. Create AGENTS.md and symlinks
    created.extend(_create_agents_and_links(root))

    # 3. CI Workflows
    created.extend(_create_workflows(root))

    # 4. Ensure .prothon section in pyproject.toml for CI config
    _ensure_prothon_ci_section(root)

    return created


def _create_docs(root: Path) -> list[Path]:
    """Create core docs/ directory and documents (SPEC, DESIGN, PATTERNS)."""
    created = []
    docs_dir = root / "docs"
    docs_dir.mkdir(parents=True, exist_ok=True)

    refs_dir = docs_dir / "references"
    refs_dir.mkdir(parents=True, exist_ok=True)
    gitkeep = refs_dir / ".gitkeep"
    if not gitkeep.exists():
        gitkeep.touch()
        created.append(gitkeep)

    src_dir = root / "src"
    if src_dir.is_dir():
        miner = ASTPatternMiner()
        idioms = miner.scan_directory(src_dir)
        if idioms:
            modules_path = refs_dir / "modules.md"
            if not modules_path.exists():
                modules_path.write_text(_REFERENCES_MODULES_HEADER + idioms)
                created.append(modules_path)

    docs = {
        "SPEC.md": _SPEC_SCAFFOLD,
        "DESIGN.md": _DESIGN_SCAFFOLD,
        "PATTERNS.md": _PATTERNS_SCAFFOLD,
    }
    for name, content in docs.items():
        path = docs_dir / name
        if not path.exists():
            path.write_text(content)
            created.append(path)
    return created


def _create_agents_and_links(root: Path) -> list[Path]:
    """Create AGENTS.md, symlinks, and skills directory."""
    created = []
    agents_path = root / "AGENTS.md"
    if not agents_path.exists():
        agents_path.write_text(_AGENTS_CONTENT)
        created.append(agents_path)

    for name in ("CLAUDE.md", "GEMINI.md", "AGENT.md"):
        link = root / name
        if not link.exists():
            try:
                os.symlink("AGENTS.md", link)
            except OSError:
                shutil.copyfile(agents_path, link)
            created.append(link)

    skills_dir = root / ".agents" / "skills"
    if not skills_dir.exists():
        skills_dir.mkdir(parents=True, exist_ok=True)
        created.append(skills_dir)
    return created


def _create_workflows(root: Path) -> list[Path]:
    """Create GitHub and GitLab CI workflow files."""
    created = []
    workflows_dir = root / ".github" / "workflows"
    workflows_dir.mkdir(parents=True, exist_ok=True)

    bump_path = workflows_dir / "version-bump.yml"
    if not bump_path.exists():
        bump_path.write_text(_VERSION_BUMP_WORKFLOW)
        created.append(bump_path)

    tag_path = workflows_dir / "version-tag.yml"
    if not tag_path.exists():
        tag_path.write_text(_VERSION_TAG_WORKFLOW)
        created.append(tag_path)

    gitlab_path = root / ".gitlab-ci.yml"
    if not gitlab_path.exists():
        gitlab_path.write_text(_GITLAB_VERSION_BUMP)
        created.append(gitlab_path)
    return created


def _ensure_prothon_ci_section(root: Path) -> None:
    """Ensure [tool.prothon.ci] section exists in pyproject.toml."""
    pyproject_path = root / "pyproject.toml"
    if not pyproject_path.exists():
        return

    try:
        content = pyproject_path.read_text()
        doc = tomlkit.parse(content)

        # Build nested structure: tool.prothon.ci
        tool = doc.setdefault("tool", tomlkit.table())
        prothon = tool.setdefault("prothon", tomlkit.table())
        ci = prothon.setdefault("ci", tomlkit.table())

        # Set default if not present
        if "auto_version" not in ci:
            ci["auto_version"] = True
            pyproject_path.write_text(tomlkit.dumps(doc))
    except Exception as exc:
        msg = f"Failed to update pyproject.toml: {exc}"
        raise ProthonError(msg) from exc
