"""Templates and scaffolds used during project adoption."""

from __future__ import annotations

from pathlib import Path

_DATA_DIR = Path(__file__).resolve().parent / "data"


def _load_template(name: str) -> str:
    return (_DATA_DIR / name).read_text(encoding="utf-8")


_SPEC_SCAFFOLD = """\
# Project Specification

<!-- Group related requirements under descriptive subheadings (e.g., ### Authentication).
     This lets AI agents focus on the group relevant to their current task. -->

## Purpose

## Requirements

## Constraints

## Out of Scope
"""

_DESIGN_SCAFFOLD = """\
# Design Document

<!-- Start each section with a one-line summary so agents can decide whether to
     read the full section. Keep sections self-contained. -->

## Architecture

## Technology Choices

## Interfaces

## Key Decisions
"""

_PATTERNS_SCAFFOLD = """\
# Implementation Patterns

> This document uses **progressive disclosure**. Signature-level module \
references live in [docs/references/modules.md](references/modules.md) \
so they can be consulted on demand without cluttering the pattern narrative.

## Code Organization

## Design Patterns

## Error Handling

## Testing Patterns
"""

_REFERENCES_MODULES_HEADER = """\
# Module Signatures

Auto-generated by `prothon init` from AST analysis of existing source code. \
Signature-only — no implementation logic (R25-R26).

"""


def get_version_bump_workflow() -> str:
    return _load_template("version-bump.yml")


def get_version_tag_workflow() -> str:
    return _load_template("version-tag.yml")


def get_gitlab_version_bump() -> str:
    return _load_template("gitlab-ci.yml")


def get_agents_content() -> str:
    return _load_template("agents.md")
