"""Templates and scaffolds used during project adoption."""

from __future__ import annotations

_SPEC_SCAFFOLD = """\
# Project Specification

## Purpose

## Requirements

## Constraints

## Out of Scope
"""

_DESIGN_SCAFFOLD = """\
# Design Document

## Architecture

## Technology Choices

## Interfaces

## Key Decisions
"""

_PATTERNS_SCAFFOLD = """\
# Implementation Patterns

> This document uses **progressive disclosure**. Signature-level module \
references live in [docs/references/modules.md](references/modules.md) \
so they can be consulted on demand without cluttering the pattern narrative.

## Code Organization

## Design Patterns

## Error Handling

## Testing Patterns
"""

_REFERENCES_MODULES_HEADER = """\
# Module Signatures

Auto-generated by `prothon init` from AST analysis of existing source code. \
Signature-only — no implementation logic (R25-R26).

"""


_VERSION_BUMP_WORKFLOW = """\
name: Version Bump

on:
  pull_request:
    branches: [main, master]
    types: [opened, synchronize]

concurrency:
  group: version-bump-${{ github.head_ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  version-bump:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check auto_version config
        id: config
        run: |
          AUTO_VERSION=$(python3 - <<'PYEOF'
          import sys
          try:
              import tomllib
          except ImportError:
              try:
                  import tomli as tomllib
              except ImportError:
                  print("true")
                  sys.exit(0)
          try:
              with open("pyproject.toml", "rb") as f:
                  data = tomllib.load(f)
              tool = data.get("tool", {})
              prothon = tool.get("prothon", {})
              ci = prothon.get("ci", {})
              val = ci.get("auto_version", True)
              print("true" if val else "false")
          except Exception:
              print("true")
          PYEOF
          )
          echo "auto_version=$AUTO_VERSION" >> "$GITHUB_OUTPUT"

      - name: Set up Python
        if: steps.config.outputs.auto_version == 'true'
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        if: steps.config.outputs.auto_version == 'true'
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Bump version
        if: steps.config.outputs.auto_version == 'true'
        run: |
          uvx prothon ci bump --before-sha "origin/${{ github.base_ref }}" --no-tag

      - name: Commit changes
        if: steps.config.outputs.auto_version == 'true'
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "chore: automatic version bump [skip ci]"
            git push origin "HEAD:${{ github.head_ref }}"
          else
            echo "No changes to commit"
          fi
"""

_VERSION_TAG_WORKFLOW = """\
name: Version Tag

on:
  push:
    branches: [main, master]

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'chore: automatic version bump')
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version
        id: get_version
        run: |
          VERSION=$(python3 - <<'PYEOF'
          try:
              import tomllib
          except ImportError:
              import tomli as tomllib
          with open("pyproject.toml", "rb") as f:
              data = tomllib.load(f)
          print(data["project"]["version"])
          PYEOF
          )
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Create Tag
        run: |
          VERSION="${{ steps.get_version.outputs.version }}"
          TAG="v${VERSION}"
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists, skipping."
            exit 0
          fi

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git tag -a "$TAG" -m "release ${VERSION}"
          git push origin "$TAG"
"""

_GITLAB_VERSION_BUMP = """\
stages:
  - version-bump

version-bump:
  stage: version-bump
  image: python:3.13
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  before_script:
    - pip install tomlkit
    - git config user.email "ci@gitlab"
    - git config user.name "GitLab CI"
  script:
    - |
      python - <<'PYEOF'
      import subprocess, sys, re, os
      from pathlib import Path

      # Read auto_version config
      try:
          import tomlkit
          doc = tomlkit.parse(Path("pyproject.toml").read_text())
          tool = doc.get("tool", {})
          prothon = tool.get("prothon", {})
          ci = prothon.get("ci", {})
          auto_version = ci.get("auto_version", True)
      except Exception:
          auto_version = True

      if not auto_version:
          print("auto_version is false \u2014 skipping version bump")
          sys.exit(0)

      # Detect changed files
      before_sha = os.environ.get("CI_COMMIT_BEFORE_SHA", "")
      current_sha = os.environ.get("CI_COMMIT_SHA", "HEAD")

      if not before_sha or before_sha == "0000000000000000000000000000000000000000":
          result = subprocess.run(
              ["git", "diff", "--name-only", "HEAD~1", "HEAD"],
              capture_output=True, text=True
          )
      else:
          result = subprocess.run(
              ["git", "diff", "--name-only", before_sha, current_sha],
              capture_output=True, text=True
          )

      if result.returncode != 0:
          print(f"git diff failed: {result.stderr}", file=sys.stderr)
          sys.exit(1)

      files = {line for line in result.stdout.strip().splitlines() if line.strip()}
      print(f"Changed files: {files}")

      # Determine bump type
      if "docs/SPEC.md" in files:
          bump_type = "major"
      elif "docs/DESIGN.md" in files:
          bump_type = "minor"
      elif "docs/PATTERNS.md" in files or any(f.startswith("src/") for f in files):
          bump_type = "patch"
      else:
          print("No relevant files changed \u2014 skipping version bump")
          sys.exit(0)

      print(f"Bump type: {bump_type}")

      # Read current version
      doc = tomlkit.parse(Path("pyproject.toml").read_text())
      current_version = doc["project"]["version"]
      print(f"Current version: {current_version}")

      # Semver arithmetic
      match = re.fullmatch(r"v?(\\d+)\\.(\\d+)\\.(\\d+)", current_version)
      if not match:
          msg = f"Invalid version format: {current_version}"
          print(msg, file=sys.stderr)
          sys.exit(1)
      major = int(match.group(1))
      minor = int(match.group(2))
      patch = int(match.group(3))

      if bump_type == "major":
          new_version = f"{major + 1}.0.0"
      elif bump_type == "minor":
          new_version = f"{major}.{minor + 1}.0"
      else:
          new_version = f"{major}.{minor}.{patch + 1}"

      print(f"New version: {new_version}")

      # Update pyproject.toml
      doc["project"]["version"] = new_version
      Path("pyproject.toml").write_text(tomlkit.dumps(doc))

      # Update src/<package>/__init__.py
      init_files = list(Path("src").glob("*/__init__.py"))
      for init_path in init_files:
          content = init_path.read_text()
          pattern = r'__version__\\s*=\\s*["\\'][^"\\']+["\\']'
          if re.search(pattern, content):
              updated = re.sub(pattern, f'__version__ = "{new_version}"', content)
              init_path.write_text(updated)
              print(f"Updated {init_path}")

      # Commit and tag
      git_add = ["git", "add", "pyproject.toml"] + [str(p) for p in init_files]
      subprocess.run(git_add, check=True)
      commit_msg = f"chore: bump version to {new_version} [skip ci]"
      subprocess.run(["git", "commit", "-m", commit_msg], check=True)
      tag_msg = f"release {new_version}"
      subprocess.run(["git", "tag", "-a", f"v{new_version}", "-m", tag_msg], check=True)

      # Push changes and tag
      server = os.environ['CI_SERVER_HOST']
      project = os.environ['CI_PROJECT_PATH']
      token = os.environ['GITLAB_TOKEN']
      remote_url = f"https://gitlab-ci-token:{token}@{server}/{project}.git"
      subprocess.run(["git", "remote", "set-url", "origin", remote_url], check=True)
      push_branch = f"HEAD:{os.environ['CI_COMMIT_BRANCH']}"
      subprocess.run(["git", "push", "origin", push_branch], check=True)
      subprocess.run(["git", "push", "origin", f"v{new_version}"], check=True)

      msg = (
          f"Successfully bumped version to {new_version} "
          f"and pushed tag v{new_version}"
      )
      print(msg)
      PYEOF
"""

_AGENTS_CONTENT = """\
# Project

## Documentation Hierarchy

This project uses a three-level documentation hierarchy. Documents are listed \
in order of authority \u2014 higher documents override lower ones when in conflict.

| Level | Document | Contains | Authority |
|-------|----------|----------|-----------|
| 1 | `docs/SPEC.md` | Requirements, constraints, scope | Highest |
| 2 | `docs/DESIGN.md` | Architecture, packages, interfaces | Medium |
| 3 | `docs/PATTERNS.md` | Code patterns, conventions, testing | Lowest |

**Rules:**
- SPEC.md must exist before DESIGN.md can be written
- DESIGN.md must exist before PATTERNS.md can be written
- When documents conflict, the higher-level document wins and lower documents \
must be amended

## Mandatory Development Workflow

All code changes \u2014 features, bug fixes, refactors \u2014 MUST follow this workflow:

### 1. Identify the Highest Affected Doc Level

- Does this change affect **requirements**? \u2192 Start at SPEC
- Does this change affect **architecture or packages**? \u2192 Start at DESIGN
- Does this change affect **code patterns**? \u2192 Start at PATTERNS
- Is this a **code-only change** with no doc impact? \u2192 Skip to step 5

### 2. Update Docs Top-Down

Starting from the highest affected level, tell the user to run the \
corresponding `prothon` CLI commands in order:

- SPEC-level change \u2192 `prothon spec`, then `prothon design`, then \
`prothon patterns`
- DESIGN-level change \u2192 `prothon design`, then `prothon patterns`
- PATTERNS-level change \u2192 `prothon patterns` only

Each command launches a separate assistant session. Do NOT invoke \
`/spec-writer`, `/design-writer`, or `/patterns-writer` directly \u2014 the user \
runs these via the CLI.

Doc harmonization and tech-researcher are handled automatically by the \
design-writer and patterns-writer skills as subagent quality gates. You do \
not need to trigger them manually.

### 5. Implement

Write the code changes.

### 6. Verify Compliance (Automatic)

**This is an always-on quality gate.** Before claiming any implementation \
work is complete, you MUST spawn a dedicated subagent (type: general-purpose, \
fresh context) to verify code matches documentation. Do not perform this \
check inline \u2014 spawn a fresh subagent: "Activate prothon-compliance-checker \
and produce a report." This ensures it gets a clean context focused solely \
on compliance verification. Report the subagent's findings to the user.

If the compliance check reports failures, fix the code or update docs and \
re-check.

For explicit full compliance scans, the user can run `prothon compliance`.

## Skills Directory

Project-specific reference skills live in `.agents/skills/` as directories \
containing `SKILL.md`. Claude Code, opencode, and Gemini CLI discover this \
directory natively \u2014 no symlinks or additional configuration needed.

When creating new skills, place them in \
`.agents/skills/<skill-name>/SKILL.md`.

## Conventions

- **Package manager:** uv
- **Task runner:** poe (poethepoet)
- **Linting:** ruff (linting + formatting)
- **Type checking:** ty
- **Testing:** pytest + hypothesis
- **Security:** bandit
- **Dead code:** vulture
- **Complexity:** complexipy
- **Pre-commit:** hooks enforce all checks on every commit

Run `poe check` before committing to verify all quality checks pass.
"""


def get_version_bump_workflow() -> str:
    return _VERSION_BUMP_WORKFLOW


def get_version_tag_workflow() -> str:
    return _VERSION_TAG_WORKFLOW


def get_gitlab_version_bump() -> str:
    return _GITLAB_VERSION_BUMP


def get_agents_content() -> str:
    return _AGENTS_CONTENT
