# Changes here will be overwritten by Copier
_src_path: gh:jackedney/prothon
project_name: prothon
module_name: kmer-counting
description: basecamp-research kmer-counting software assignment
author_name: Jack Edney
author_email: jack.edney@outlook.com
python_version: 3.13
license: None
